version: '3.6'

services:
  php:
    container_name: magento2_php
    build:
      context: .
      dockerfile: ./.docker/build/php/Dockerfile
    image: magento2/php:7.3.8-fpm-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./.docker/bin/*:/usr/local/bin/
      - ./.docker/build/php/startup.sh:/home/scripts/startup.sh
      - ./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql

  nginx:
    container_name: magento2_nginx
    image: nginx:1.17.6-alpine
    volumes:
      - ./src:/var/www/html
      - ./.docker/config/nginx/magento.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - php

  mysql:
    container_name: magento2_mysql
    image: mysql:5.7.28
    volumes:
      - ./.docker/volumes/mysql/data:/var/lib/mysql
      - ./.docker/volumes/mysql/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_DATABASE: magento
    ports:
      - 3306:3306